[package]
name = "circle-sys"
version = "0.1.0"
edition = "2018"
links = "circle_shim"

#[lib]
#crate-type = ["staticlib"]

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
