name: "Build BoldOS"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/bold-build.yaml"
      - "src/*"
      - "scripts/prepare_kernel_accessories.sh"
      - "Cargo.{toml,lock}"
      - "targets/*"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: wazzaps/boldos-build
      volumes:
        - ${{github.workspace}}:/wd
      env:
        HOME: /root
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache Cargo packages and target
        uses: actions/cache@v2
        with:
          path: |
            /root/.cargo/registry/index/
            /root/.cargo/registry/cache/
            /root/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --verbose
      - name: ls target
        run: ls target/**
      - name: Clippy
        run: cargo clippy --release
#        continue-on-error: true
      - name: Build Kernel Accessories
        run: ./scripts/prepare_kernel_accessories.sh target/aarch64-none-elf/release/boldos
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-aarch64
          path: |
            target/aarch64-none-elf/release/boldos
            target/aarch64-none-elf/release/boldos.bin
            target/aarch64-none-elf/release/initrd.tar
            target/aarch64-none-elf/release/disk.img
          if-no-files-found: error
