name: "Build BoldOS"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: wazzaps/boldos-build
      volumes:
        - ${{github.workspace}}:/wd
      env:
        HOME: /root
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache Cargo packages
        uses: actions/cache@v2
        with:
          key: boldos-caches-2
          path: |
            /root/.cargo/registry
            /wd/target
      - name: Build
        run: cargo build --release
      - name: Clippy
        run: cargo clippy --release
#        continue-on-error: true
      - name: Build Kernel Accessories
        run: ./scripts/prepare_kernel_accessories.sh target/aarch64-none-elf/release/boldos
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-aarch64
          path: |
            /wd/target/aarch64-none-elf/release/boldos
            /wd/target/aarch64-none-elf/release/boldos.bin
            /wd/target/aarch64-none-elf/release/initrd.tar
            /wd/target/aarch64-none-elf/release/disk.img
          if-no-files-found: error
