name: "Pull Request Labeler"
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ github.token }}
          sync_lables: true
      - name: Label the PR size
        uses: codelytv/pr-size-labeler@v1.6.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          xs_max_size: "10"
          s_max_size: "100"
          m_max_size: "500"
          l_max_size: "1000"
          fail_if_xl: "false"
          message_if_xl: >
            'This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.’
          github_api_url: "api.github.com"
